name: bmicalculator
description: A simple Flutter project which used to tell you about your weight.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true

  assets:
   - images/kardo.jpg

  fonts:
    - family: Sarchia
      fonts:
        - asset: fonts/sarchia.ttf
  